### PR TITLE
Add a new folder components and new Home.js file

### PR DESCRIPTION
**Pull request by dfine907**

### CODE REVIEW

**Comment by dfine907** [comment]
On this branch for this pull request, I removed the global css (we don't need it) and added a components folder along with a simple home page component and css module for the home styles. 
Additionally I created a dynamic router folder just so we can see how it works.

**Review by JoshuaCMorgan — APPROVED** [review]
I have some suggestions on changes that we work out at a later time.  For instance, the proposal for Layout component.

**Review by curlygirltech — APPROVED** [review]
Looks great

**Comment by dfine907** [comment]
I will now create a new branch for continue work on app.

**Pull request merged**
